#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 800
#define WINDOW_BACKGROUND sf::Color::White
#define IS_VSYNC_ENABLED true
#define FIELD_TOTAL_CELLS 3
#define FIELD_PADDING 5.f
#define EMPTY_FIELD_CHAR '_'
#define X_FIELD_CHAR 'X'
#define O_FIELD_CHAR 'O'